spring.data.mongodb.uri=mongodb+srv://virusinferno:Datboi20@chillclipscluster.wmh8xcp.mongodb.net/movieDB?appName=ChillClipsCluster
server.port=8080
jwt.secret=ChillClipsSecretKey2026VirusInfernoDigitalStudio
jwt.expiration=86400000